### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by MBrill** [IT-Analyst/Git-Test-Repo#1]
Hallo Fabian,
ich habe noch ein Paar Typos im master-branch in README.md korrigiert! Sollten wir jetzt public machen!

**Comment by fkalweit** [comment]
Bin so gegen 10 im Büro. Kümmere mich dann darum.

-------- Ursprüngliche Nachricht --------
Von: Manfred Brill notifications@github.com 
Datum: 19.09.2016  08:43  (GMT+01:00) 
An: IT-Analyst/Git-Test-Repo Git-Test-Repo@noreply.github.com 
Betreff: [IT-Analyst/Git-Test-Repo] Typos (#1) 

Hallo Fabian,

ich habe noch ein Paar Typos im master-branch in README.md korrigiert! Sollten wir jetzt public machen!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/IT-Analyst/Git-Test-Repo","title":"IT-Analyst/Git-Test-Repo","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/IT-Analyst/Git-Test-Repo"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Typos (#1)"}],"action":{"name":"View Issue","url":"https://github.com/IT-Analyst/Git-Test-Repo/issues/1"}}}
